# Generated by Django 4.0.3 on 2022-03-27 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Name_Subscriber',
            fields=[
                ('name', models.CharField(max_length=21, primary_key=True, serialize=False, unique=True, verbose_name='Group Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber_Group', to='Notification.group_name_subscriber')),
                ('uesrs', models.ManyToManyField(related_name='Subscriber_Group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
