# Generated by Django 4.0.3 on 2022-03-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_Name_Subscriber',
            new_name='Subscriber_Group_Name',
        ),
    ]
