# Generated by Django 4.0.3 on 2022-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_rename_group_name_subscriber_subscriber_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(max_length=22)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscriber_Group',
        ),
        migrations.DeleteModel(
            name='Subscriber_Group_Name',
        ),
    ]
